Use `pyproject.toml` to specify build requirements
Also:
- Execute `build_ext` when running `sdist`.
- Use PyPA `build` package to build the sdist.
- Move most metadata from `setup.py` to `setup.cfg`
- Build wheels using `oldest-supported-numpy` instead of the latest
  `numpy`. In this way, the generated wheels will be forward-compatible
  with newer numpy versions and we prevent errors like:

```
>>> from bx.bbi.bigbed_file import BigBedFile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/bx/bbi/bigbed_file.pyx", line 1, in init bx.bbi.bigbed_file
  File "lib/bx/bbi/bbi_file.pyx", line 1, in init bx.bbi.bbi_file
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```